services:
  - type: web
    name: portfolio-backend
    env: python
    pythonVersion: 3.11.8
    buildCommand: pip install -r requirements.txt
    startCommand: |
      python manage.py migrate --noinput &&
      gunicorn portfolio_backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: portfolio_backend.settings