services:
  - type: web
    name: portfolio-backend
    env: python
    pythonVersion: 3.11.8

    buildCommand: |
      pip install -r requirements.txt
      python manage.py makemigrations
      python manage.py migrate --noinput

    startCommand: gunicorn portfolio_backend.wsgi:application

    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: portfolio_backend.settings